[project]
name = "gracemo-adapters"
version = "0.0.1"
description = "Workspace for GRaCEmo ViRa Python Adapters"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyaudio",
]

[tool.uv.workspace]
members = [
    "sdk",
    "robot-bridge",
    "vision",
    "voice",
    "brain",
]

[tool.uv.sources]
gracemo-sdk = { workspace = true }
