[package]
name = "gracemo-k"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
gracemo-types = { path = "../gracemo-types" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
