<?xml version='1.0' encoding='UTF-8'?>
<package format="3">
  <name>gracemo_interfaces</name>
  <version>0.0.0</version>
  <description>GraceEMO custom message, service, and action definitions</description>
  <maintainer email="root@todo.todo">root</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>action_msgs</depend>
  <depend>builtin_interfaces</depend>
  <depend>rosidl_default_generators</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
<member_of_group>rosidl_interface_packages</member_of_group><exec_depend>rosidl_default_runtime</exec_depend></package>